In [1]:
import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv(r"Processed Datasets\final_train.csv")

train.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,pos_avg_dpd,pos_max_dpd,pos_avg_dpd_def,pos_max_dpd_def,pos_late_payment_count,pos_serious_dpd_count,pos_active_contracts,pos_completed_contracts,pos_signed_contracts,pos_demand_contracts
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0.0,0.0,0.0,0.0,0.0,0.0,19.0,0.0,0.0,0.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0.0,0.0,0.0,0.0,0.0,0.0,26.0,2.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0.0,0.0,0.0,0.0,0.0,0.0,18.0,2.0,0.0,0.0
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0.0,0.0,0.0,0.0,0.0,0.0,62.0,3.0,1.0,0.0

In [3]:
test = pd.read_csv(r"Processed Datasets\final_test.csv")
test.head()

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,pos_avg_dpd,pos_max_dpd,pos_avg_dpd_def,pos_max_dpd_def,pos_late_payment_count,pos_serious_dpd_count,pos_active_contracts,pos_completed_contracts,pos_signed_contracts,pos_demand_contracts
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,...,0.777778,7.0,0.777778,7.0,1.0,1.0,7.0,2.0,0.0,0.0
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,9.0,1.0,1.0,0.0
2,100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,...,0.944444,18.0,0.000000,0.0,2.0,0.0,32.0,3.0,1.0,0.0
3,100028,Cash loans,F,N,Y,2,315000.0,1575000.0,49018.5,1575000.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,29.0,2.0,0.0,0.0
4,100038,Cash loans,M,Y,N,1,180000.0,625500.0,32067.0,625500.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,12.0,1.0,0.0,0.0

In [4]:
cat_cols = train.drop(columns=['TARGET', 'SK_ID_CURR']).select_dtypes(include=['object', 'str']).columns
cat_cols

Index(['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY',
       'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE',
       'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE', 'FONDKAPREMONT_MODE',
       'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE'],
      dtype='str')

In [5]:
numeric_cols = train.select_dtypes(include="number")
inf_cols = numeric_cols.columns[np.isinf(numeric_cols).any()]
inf_cols

Index(['inst_avg_payment_ratio', 'inst_min_payment_ratio'], dtype='str')

In [6]:
all_nan = train.columns[train.isna().all()]

print(all_nan)

Index([], dtype='str')

In [7]:
train.replace([np.inf, -np.inf], np.nan, inplace=True)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,pos_avg_dpd,pos_max_dpd,pos_avg_dpd_def,pos_max_dpd_def,pos_late_payment_count,pos_serious_dpd_count,pos_active_contracts,pos_completed_contracts,pos_signed_contracts,pos_demand_contracts
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0.000000,0.0,0.000000,0.0,0.0,0.0,19.0,0.0,0.0,0.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0.000000,0.0,0.000000,0.0,0.0,0.0,26.0,2.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,3.0,1.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0.000000,0.0,0.000000,0.0,0.0,0.0,18.0,2.0,0.0,0.0
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0.000000,0.0,0.000000,0.0,0.0,0.0,62.0,3.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,7.0,1.0,1.0,0.0
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,...,0.000000,0.0,0.000000,0.0,0.0,0.0,6.0,1.0,0.0,0.0
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,...,0.294118,5.0,0.294118,5.0,1.0,1.0,15.0,2.0,0.0,0.0
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,20.0,0.0,0.0,0.0
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,...,0.070423,5.0,0.070423,5.0,1.0,1.0,65.0,6.0,0.0,0.0

In [8]:


summary = []

for col in numeric_cols.columns:

    Q1 = train[col].quantile(0.25)
    Q3 = train[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outlier_mask = (train[col] < lower) | (train[col] > upper)

    outlier_count = outlier_mask.sum()
    outlier_pct = round(outlier_count / len(train) * 100, 2)

    skew = round(train[col].skew(), 2)

    missing_pct = round(train[col].isna().mean() * 100, 2)

    minimum = train[col].min()
    maximum = train[col].max()

    unique = train[col].nunique()

    # ---------- Decision ----------
    if col == "TARGET":
        decision = "Target"
    elif col.startswith("SK_ID"):
        decision = "Ignore (ID)"
    elif train[col].nunique() <= 2:
        decision = "Binary"
    elif col == "DAYS_EMPLOYED":
        decision = "Replace sentinel"
    elif outlier_pct < 5:
        decision = "Keep"
    elif outlier_pct < 20:
        decision = "Review"
    else:
        decision = "Investigate"

    summary.append({
        "Feature": col,
        "Outlier %": outlier_pct,
        "Skew": skew,
        "Missing %": missing_pct,
        "Min": minimum,
        "Max": maximum,
        "Unique": unique,
        "Decision": decision
    })

outlier_summary = (
    pd.DataFrame(summary)
      .sort_values("Outlier %", ascending=False)
      .reset_index(drop=True)
)

print(outlier_summary)

                         Feature  Outlier %    Skew  Missing %           Min  \
0           REGION_RATING_CLIENT      26.19    0.09       0.00      1.000000
1    REGION_RATING_CLIENT_W_CITY      25.37    0.06       0.00      1.000000
2                  DAYS_EMPLOYED      23.48    1.66       0.00 -17912.000000
3         REG_CITY_NOT_WORK_CITY      23.05    1.28       0.00      0.000000
4         inst_avg_payment_ratio      20.44  159.90       5.17      0.333333
..                           ...        ...     ...        ...           ...
218       inst_min_payment_ratio       0.00   -0.34       5.16      0.000000
219           cc_avg_utilization       0.00    0.56      72.02      0.000000
220           cc_max_utilization       0.00   -0.37      72.02      0.000000
221             cc_oldest_record       0.00   -0.77      71.74    -96.000000
222            pos_oldest_record       0.00   -0.04       5.88    -96.000000

               Max  Unique          Decision
0         3.000000       3       Investigate
1         3.000000       3       Investigate
2    365243.000000   12574  Replace sentinel
3         1.000000       2            Binary
4      8482.446155   42694       Investigate
..             ...     ...               ...
218       1.600495  116715              Keep
219       2.138790   59083              Keep
220       5.000000   56087              Keep
221      -1.000000      96              Keep
222      -1.000000      96              Keep

[223 rows x 8 columns]

In [9]:
count_cols = [
    "CNT_CHILDREN",
    "CNT_FAM_MEMBERS",

    "bureau_loan_count",
    "bureau_active_loans",
    "bureau_closed_loans",
    "bureau_sold_loans",
    "bureau_bad_debt_loans",
    "bureau_credit_prolong_count",

    "prev_application_count",
    "prev_approved_count",
    "prev_refused_count",
    "prev_canceled_count",
    "prev_unused_offer_count",

    "inst_late_payment_count",
    "inst_underpaid_count",
    "inst_count",

    "cc_card_count",
    "cc_late_payment_count",
    "cc_serious_dpd_count",

    "pos_loan_count",
    "pos_late_payment_count",
    "pos_serious_dpd_count",
    "pos_active_contracts",
    "pos_completed_contracts",
    "pos_signed_contracts",
    "pos_demand_contracts"
]

for col in count_cols:
    print(f"{col}: {train[col].value_counts().max()}")

CNT_CHILDREN: 215371
CNT_FAM_MEMBERS: 158357
bureau_loan_count: 36072
bureau_active_loans: 74103
bureau_closed_loans: 53505
bureau_sold_loans: 258265
bureau_bad_debt_loans: 263471
bureau_credit_prolong_count: 254983
prev_application_count: 52533
prev_approved_count: 76640
prev_refused_count: 190763
prev_canceled_count: 180331
prev_unused_offer_count: 272024
inst_late_payment_count: 136644
inst_underpaid_count: 166497
inst_count: 12295
cc_card_count: 86363
cc_late_payment_count: 69023
cc_serious_dpd_count: 72063
pos_loan_count: 89514
pos_late_payment_count: 234761
pos_serious_dpd_count: 249554
pos_active_contracts: 16491
pos_completed_contracts: 104597
pos_signed_contracts: 231574
pos_demand_contracts: 289132

In [10]:
train.loc[train["inst_avg_payment_ratio"] > 100, [
    "inst_avg_payment_ratio",
    "inst_total_payment",
    "inst_count",
    "TARGET"
]].sort_values("inst_avg_payment_ratio", ascending=False)

        inst_avg_payment_ratio  inst_total_payment  inst_count  TARGET
182837             8482.446155          180779.175        13.0       0
91368              5012.580645          753465.015        31.0       0
93593              4981.743590          673851.780        39.0       0
54927              4697.787881          689422.095        11.0       1
34468              4376.915391         2797307.415        17.0       0
...                        ...                 ...         ...     ...
116436              104.874684         1397515.995        56.0       0
299285              103.987687         1021496.670        17.0       1
216595              102.066361         1209440.295        29.0       0
193298              101.725354         1267464.645        23.0       1
240215              100.635108         2050176.240        14.0       0

[140 rows x 4 columns]

In [11]:
train["inst_avg_payment_ratio"] = (
    train["inst_avg_payment_ratio"]
    .replace([np.inf, -np.inf], np.nan)
)

In [12]:
train["inst_avg_payment_ratio"].describe(percentiles=[0.95,0.99,0.995,0.999])

count    291617.000000
mean          1.382986
std          30.179742
min           0.333333
95%           1.248018
99%           2.074076
99.5%         2.821784
99.9%        23.810860
max        8482.446155
Name: inst_avg_payment_ratio, dtype: float64

In [14]:
# Remove impossible counts
count_cols = [
        "CNT_CHILDREN",
        "CNT_FAM_MEMBERS",
        "bureau_loan_count",
        "bureau_active_loans",
        "bureau_closed_loans",
        "bureau_sold_loans",
        "bureau_bad_debt_loans",
        "bureau_credit_prolong_count",
        "prev_application_count",
        "prev_approved_count",
        "prev_refused_count",
        "prev_canceled_count",
        "prev_unused_offer_count",
        "inst_late_payment_count",
        "inst_underpaid_count",
        "inst_count",
        "cc_card_count",
        "cc_late_payment_count",
        "cc_serious_dpd_count",
        "pos_loan_count",
        "pos_late_payment_count",
        "pos_serious_dpd_count",
        "pos_active_contracts",
        "pos_completed_contracts",
        "pos_signed_contracts",
        "pos_demand_contracts",
    ]

for col in count_cols:
    if (train[col] < 0).any():
        print(col, (train[col] < 0).sum())