In [2]:
import pandas as pd
import numpy as np

In [3]:
train = pd.read_csv(r"Processed Datasets\final_train.csv")

train.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,pos_avg_dpd,pos_max_dpd,pos_avg_dpd_def,pos_max_dpd_def,pos_late_payment_count,pos_serious_dpd_count,pos_active_contracts,pos_completed_contracts,pos_signed_contracts,pos_demand_contracts
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0.0,0.0,0.0,0.0,0.0,0.0,19.0,0.0,0.0,0.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0.0,0.0,0.0,0.0,0.0,0.0,26.0,2.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0.0,0.0,0.0,0.0,0.0,0.0,18.0,2.0,0.0,0.0
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0.0,0.0,0.0,0.0,0.0,0.0,62.0,3.0,1.0,0.0

In [4]:
test = pd.read_csv(r"Processed Datasets\final_test.csv")
test.head()

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,pos_avg_dpd,pos_max_dpd,pos_avg_dpd_def,pos_max_dpd_def,pos_late_payment_count,pos_serious_dpd_count,pos_active_contracts,pos_completed_contracts,pos_signed_contracts,pos_demand_contracts
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,...,0.777778,7.0,0.777778,7.0,1.0,1.0,7.0,2.0,0.0,0.0
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,9.0,1.0,1.0,0.0
2,100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,...,0.944444,18.0,0.000000,0.0,2.0,0.0,32.0,3.0,1.0,0.0
3,100028,Cash loans,F,N,Y,2,315000.0,1575000.0,49018.5,1575000.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,29.0,2.0,0.0,0.0
4,100038,Cash loans,M,Y,N,1,180000.0,625500.0,32067.0,625500.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,12.0,1.0,0.0,0.0

In [5]:
cat_cols = train.drop(columns=['TARGET', 'SK_ID_CURR']).select_dtypes(include=['object', 'str']).columns
cat_cols

Index(['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY',
       'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE',
       'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE', 'FONDKAPREMONT_MODE',
       'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE'],
      dtype='str')

In [22]:
numeric_cols = train.select_dtypes(include="number")
inf_cols = numeric_cols.columns[np.isinf(numeric_cols).any()]
inf_cols

Index([], dtype='str')

In [17]:
all_nan = train.columns[train.isna().all()]

print(all_nan)

Index([], dtype='str')

In [21]:
train.replace([np.inf, -np.inf], np.nan, inplace=True)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,pos_avg_dpd,pos_max_dpd,pos_avg_dpd_def,pos_max_dpd_def,pos_late_payment_count,pos_serious_dpd_count,pos_active_contracts,pos_completed_contracts,pos_signed_contracts,pos_demand_contracts
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0.000000,0.0,0.000000,0.0,0.0,0.0,19.0,0.0,0.0,0.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0.000000,0.0,0.000000,0.0,0.0,0.0,26.0,2.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,3.0,1.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0.000000,0.0,0.000000,0.0,0.0,0.0,18.0,2.0,0.0,0.0
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0.000000,0.0,0.000000,0.0,0.0,0.0,62.0,3.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,7.0,1.0,1.0,0.0
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,...,0.000000,0.0,0.000000,0.0,0.0,0.0,6.0,1.0,0.0,0.0
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,...,0.294118,5.0,0.294118,5.0,1.0,1.0,15.0,2.0,0.0,0.0
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,20.0,0.0,0.0,0.0
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,...,0.070423,5.0,0.070423,5.0,1.0,1.0,65.0,6.0,0.0,0.0

Index([], dtype='str')

In [23]:


summary = []

for col in numeric_cols.columns:

    Q1 = train[col].quantile(0.25)
    Q3 = train[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outlier_mask = (train[col] < lower) | (train[col] > upper)

    outlier_count = outlier_mask.sum()
    outlier_pct = round(outlier_count / len(train) * 100, 2)

    skew = round(train[col].skew(), 2)

    missing_pct = round(train[col].isna().mean() * 100, 2)

    minimum = train[col].min()
    maximum = train[col].max()

    unique = train[col].nunique()

    # ---------- Decision ----------
    if col == "TARGET":
        decision = "Target"
    elif col.startswith("SK_ID"):
        decision = "Ignore (ID)"
    elif train[col].nunique() <= 2:
        decision = "Binary"
    elif col == "DAYS_EMPLOYED":
        decision = "Replace sentinel"
    elif outlier_pct < 5:
        decision = "Keep"
    elif outlier_pct < 20:
        decision = "Review"
    else:
        decision = "Investigate"

    summary.append({
        "Feature": col,
        "Outlier %": outlier_pct,
        "Skew": skew,
        "Missing %": missing_pct,
        "Min": minimum,
        "Max": maximum,
        "Unique": unique,
        "Decision": decision
    })

outlier_summary = (
    pd.DataFrame(summary)
      .sort_values("Outlier %", ascending=False)
      .reset_index(drop=True)
)

outlier_summary

,Feature,Outlier %,Skew,Missing %,Min,Max,Unique,Decision
0,REGION_RATING_CLIENT,26.19,0.09,0.00,1.000000,3.000000,3,Investigate
1,REGION_RATING_CLIENT_W_CITY,25.37,0.06,0.00,1.000000,3.000000,3,Investigate
2,DAYS_EMPLOYED,23.48,1.66,0.00,-17912.000000,365243.000000,12574,Replace sentinel
3,REG_CITY_NOT_WORK_CITY,23.05,1.28,0.00,0.000000,1.000000,2,Binary
4,inst_avg_payment_ratio,20.44,159.90,5.17,0.333333,8482.446155,42694,Investigate
...,...,...,...,...,...,...,...,...
218,inst_min_payment_ratio,0.00,-0.34,5.16,0.000000,1.600495,116715,Keep
219,cc_avg_utilization,0.00,0.56,72.02,0.000000,2.138790,59083,Keep
220,cc_max_utilization,0.00,-0.37,72.02,0.000000,5.000000,56087,Keep
221,cc_oldest_record,0.00,-0.77,71.74,-96.000000,-1.000000,96,Keep
222,pos_oldest_record,0.00,-0.04,5.88,-96.000000,-1.000000,96,Keep

In [29]:
count_cols = [
    "CNT_CHILDREN",
    "CNT_FAM_MEMBERS",

    "bureau_loan_count",
    "bureau_active_loans",
    "bureau_closed_loans",
    "bureau_sold_loans",
    "bureau_bad_debt_loans",
    "bureau_credit_prolong_count",

    "prev_application_count",
    "prev_approved_count",
    "prev_refused_count",
    "prev_canceled_count",
    "prev_unused_offer_count",

    "inst_late_payment_count",
    "inst_underpaid_count",
    "inst_count",

    "cc_card_count",
    "cc_late_payment_count",
    "cc_serious_dpd_count",

    "pos_loan_count",
    "pos_late_payment_count",
    "pos_serious_dpd_count",
    "pos_active_contracts",
    "pos_completed_contracts",
    "pos_signed_contracts",
    "pos_demand_contracts"
]

for col in count_cols:
    print(train[col].value_counts().sort_index())
    print(test[col].value_counts().sort_index())

CNT_CHILDREN
0     215371
1      61119
2      26749
3       3717
4        429
5         84
6         21
7          7
8          2
9          2
10         2
11         1
12         2
14         3
19         2
Name: count, dtype: int64
CNT_CHILDREN
0     34685
1      9504
2      3949
3       535
4        49
5        12
6         3
7         1
8         3
11        2
20        1
Name: count, dtype: int64
CNT_FAM_MEMBERS
1.0      67847
2.0     158357
3.0      52601
4.0      24697
5.0       3478
6.0        408
7.0         81
8.0         20
9.0          6
10.0         3
11.0         1
12.0         2
13.0         1
14.0         2
15.0         1
16.0         2
20.0         2
Name: count, dtype: int64
CNT_FAM_MEMBERS
1.0     10251
2.0     26054
3.0      8173
4.0      3690
5.0       512
6.0        43
7.0        12
8.0         2
9.0         1
10.0        3
13.0        2
21.0        1
Name: count, dtype: int64
bureau_loan_count
1.0      36072
2.0      35635
3.0      32925
4.0      28973
5.0      24985
6.0      20952
7.0      17273
8.0      14356
9.0      11156
10.0      8887
11.0      7195
12.0      5566
13.0      4376
14.0      3497
15.0      2549
16.0      1996
17.0      1650
18.0      1280
19.0       951
20.0       748
21.0       542
22.0       444
23.0       296
24.0       253
25.0       180
26.0       162
27.0       123
28.0       106
29.0        69
30.0        40
31.0        50
32.0        51
33.0        24
34.0        16
35.0        11
36.0        14
37.0        12
38.0        16
39.0         6
40.0         5
41.0         8
42.0         3
43.0         3
44.0         3
45.0         3
47.0         6
48.0         2
49.0         3
50.0         3
51.0         2
52.0         1
53.0         1
54.0         3
55.0         2
56.0         1
58.0         1
59.0         1
61.0         1
94.0         1
116.0        1
Name: count, dtype: int64
bureau_loan_count
1.0     5448
2.0     5369
3.0     4903
4.0     4494
5.0     3928
6.0     3377
7.0     2822
8.0     2380
9.0     1917
10.0    1631
11.0    1261
12.0     998
13.0     768
14.0     632
15.0     512
16.0     398
17.0     319
18.0     233
19.0     182
20.0     138
21.0     140
22.0     101
23.0      85
24.0      51
25.0      37
26.0      38
27.0      19
28.0      29
29.0      19
30.0      16
31.0       8
32.0       9
33.0       9
34.0       9
35.0       7
36.0       8
37.0       1
38.0       3
39.0       3
40.0       5
41.0       2
44.0       1
45.0       2
46.0       1
47.0       2
55.0       2
57.0       1
60.0       1
78.0       1
Name: count, dtype: int64
bureau_active_loans
0.0     46341
1.0     74103
2.0     58383
3.0     38011
4.0     22041
5.0     12051
6.0      6107
7.0      3156
8.0      1648
9.0       780
10.0      425
11.0      220
12.0      111
13.0       51
14.0       27
15.0       14
16.0        5
17.0        7
18.0        2
19.0        4
20.0        1
22.0        2
32.0        1
Name: count, dtype: int64
bureau_active_loans
0.0      7655
1.0     11385
2.0      9126
3.0      6100
4.0      3787
5.0      2093
6.0      1103
7.0       544
8.0       271
9.0       139
10.0       64
11.0       24
12.0       16
13.0        5
14.0        1
15.0        3
17.0        1
18.0        1
19.0        2
Name: count, dtype: int64
bureau_closed_loans
0.0      33326
1.0      53505
2.0      43091
3.0      33669
4.0      25914
5.0      19641
6.0      14610
7.0      10919
8.0       7651
9.0       5635
10.0      4156
11.0      3073
12.0      2195
13.0      1674
14.0      1183
15.0       880
16.0       617
17.0       431
18.0       319
19.0       244
20.0       173
21.0       133
22.0        84
23.0        88
24.0        58
25.0        52
26.0        29
27.0        27
28.0        18
29.0        17
30.0        10
31.0         8
32.0         9
33.0         5
34.0         2
35.0         6
36.0         4
37.0         2
38.0         1
39.0         4
40.0         5
41.0         1
42.0         3
43.0         2
44.0         1
45.0         1
46.0         2
47.0         3
48.0         4
51.0         1
52.0         2
56.0         1
84.0         1
108.0        1
Name: count, dtype: int64
bureau_closed_loans
0.0     4560
1.0     8190
2.0     6641
3.0     5416
4.0     4276
5.0     3235
6.0     2522
7.0     1910
8.0     1440
9.0     1001
10.0     787
11.0     572
12.0     414
13.0     336
14.0     231
15.0     181
16.0     169
17.0      90
18.0      79
19.0      59
20.0      42
21.0      35
22.0      23
23.0      14
24.0      13
25.0      16
26.0      12
27.0       8
28.0       9
29.0       3
30.0       4
31.0       5
33.0       9
34.0       6
35.0       2
36.0       3
38.0       2
45.0       1
52.0       1
53.0       1
58.0       1
66.0       1
Name: count, dtype: int64
bureau_sold_loans
0.0    258265
1.0      4855
2.0       333
3.0        29
4.0         5
5.0         2
6.0         1
9.0         1
Name: count, dtype: int64
bureau_sold_loans
0.0    41525
1.0      737
2.0       47
3.0        7
5.0        2
6.0        2
Name: count, dtype: int64
bureau_bad_debt_loans
0.0    263471
1.0        20
Name: count, dtype: int64
bureau_bad_debt_loans
0.0    42319
1.0        1
Name: count, dtype: int64
bureau_credit_prolong_count
0.0    254983
1.0      6869
2.0      1282
3.0       256
4.0        61
5.0        29
6.0         7
7.0         1
8.0         1
9.0         2
Name: count, dtype: int64
bureau_credit_prolong_count
0.0    42032
1.0      246
2.0       37
3.0        3
4.0        1
5.0        1
Name: count, dtype: int64
prev_application_count
1.0     52533
2.0     45799
3.0     40014
4.0     32922
5.0     26638
        ...
64.0        2
67.0        1
68.0        1
72.0        1
73.0        1
Name: count, Length: 65, dtype: int64
prev_application_count
1.0     7925
2.0     6938
3.0     5952
4.0     5237
5.0     4248
6.0     3515
7.0     2832
8.0     2300
9.0     1860
10.0    1426
11.0    1101
12.0     888
13.0     735
14.0     566
15.0     443
16.0     326
17.0     306
18.0     217
19.0     206
20.0     154
21.0     115
22.0      84
23.0      76
24.0      55
25.0      47
26.0      50
27.0      38
28.0      25
29.0      30
30.0      24
31.0       8
32.0      12
33.0       6
34.0      10
35.0       6
36.0       6
37.0       4
38.0       2
39.0       5
40.0       4
41.0       3
42.0       1
43.0       6
44.0       4
46.0       1
60.0       1
66.0       1
77.0       1
Name: count, dtype: int64
prev_approved_count
0.0       992
1.0     76640
2.0     67388
3.0     52238
4.0     35664
5.0     23157
6.0     14329
7.0      8615
8.0      4982
9.0      2945
10.0     1745
11.0      958
12.0      587
13.0      335
14.0      202
15.0      101
16.0       60
17.0       39
18.0       37
19.0       21
20.0       10
21.0        5
22.0        2
23.0        2
24.0        2
27.0        1
Name: count, dtype: int64
prev_approved_count
0.0       167
1.0     11729
2.0     11059
3.0      8582
4.0      6055
5.0      3885
6.0      2525
7.0      1477
8.0       950
9.0       524
10.0      362
11.0      188
12.0      114
13.0       82
14.0       45
15.0       31
16.0       14
17.0        5
18.0        1
19.0        5
Name: count, dtype: int64
prev_refused_count
0.0     190763
1.0      46534
2.0      22739
3.0      11859
4.0       6904
5.0       4091
6.0       2637
7.0       1746
8.0       1030
9.0        732
10.0       543
11.0       366
12.0       288
13.0       203
14.0       135
15.0       125
16.0        81
17.0        47
18.0        47
19.0        42
20.0        21
21.0        18
22.0        16
23.0         9
24.0        18
25.0         9
26.0         9
27.0         6
28.0         5
29.0         5
30.0         3
31.0         3
32.0         4
33.0         2
34.0         1
35.0         2
36.0         2
37.0         2
39.0         2
41.0         2
43.0         1
47.0         1
51.0         1
54.0         1
58.0         1
68.0         1
Name: count, dtype: int64
prev_refused_count
0.0     29817
1.0      8082
2.0      4054
3.0      2166
4.0      1339
5.0       768
6.0       510
7.0       323
8.0       217
9.0       139
10.0      113
11.0       71
12.0       52
13.0       30
14.0       22
15.0       24
16.0       13
17.0       15
18.0        7
19.0        6
20.0        7
21.0        7
22.0        5
23.0        2
25.0        3
26.0        2
27.0        2
34.0        1
37.0        1
41.0        1
64.0        1
Name: count, dtype: int64
prev_canceled_count
0.0     180331
1.0      50013
2.0      26122
3.0      14358
4.0       8173
5.0       4770
6.0       2743
7.0       1653
8.0        975
9.0        627
10.0       439
11.0       245
12.0       186
13.0       124
14.0        96
15.0        62
16.0        32
17.0        26
18.0        15
19.0        13
20.0        11
21.0        10
22.0         5
23.0         4
24.0         5
25.0         4
26.0         2
27.0         1
28.0         2
30.0         1
31.0         1
34.0         1
38.0         1
40.0         1
44.0         1
51.0         1
52.0         1
57.0         1
58.0         1
Name: count, dtype: int64
prev_canceled_count
0.0     25832
1.0      8946
2.0      5013
3.0      3024
4.0      1874
5.0      1154
6.0       695
7.0       435
8.0       285
9.0       188
10.0      106
11.0       80
12.0       55
13.0       35
14.0       21
15.0       15
16.0        9
17.0       10
18.0        5
19.0        7
20.0        3
21.0        3
22.0        2
24.0        1
39.0        1
40.0        1
Name: count, dtype: int64
prev_unused_offer_count
0.0     272024
1.0      16119
2.0       2332
3.0        427
4.0        114
5.0         21
6.0         11
7.0          2
8.0          5
10.0         1
16.0         1
Name: count, dtype: int64
prev_unused_offer_count
0.0     44754
1.0      2593
2.0       346
3.0        79
4.0        17
5.0         9
9.0         1
21.0        1
Name: count, dtype: int64
inst_late_payment_count
0.0      136644
1.0       37002
2.0       21685
3.0       15711
4.0       12275
          ...
108.0         2
113.0         1
121.0         1
136.0         1
159.0         1
Name: count, Length: 102, dtype: int64
inst_late_payment_count
0.0     23098
1.0      6332
2.0      3656
3.0      2583
4.0      1935
        ...
80.0        2
83.0        1
90.0        1
91.0        1
99.0        1
Name: count, Length: 76, dtype: int64
inst_underpaid_count
0.0      166497
1.0         801
2.0       39116
3.0         981
4.0       19762
          ...
131.0         1
135.0         1
136.0         1
143.0         1
154.0         1
Name: count, Length: 126, dtype: int64
inst_underpaid_count
0.0      27754
1.0        122
2.0       6620
3.0        145
4.0       3355
         ...
98.0         1
100.0        1
103.0        1
123.0        1
125.0        1
Name: count, Length: 91, dtype: int64
inst_count
1.0       692
2.0       627
3.0      2473
4.0      5720
5.0      5385
         ...
337.0       1
344.0       1
347.0       1
350.0       1
372.0       1
Name: count, Length: 319, dtype: int64
inst_count
1.0       280
2.0       219
3.0       419
4.0      1010
5.0       936
         ...
310.0       1
313.0       1
318.0       1
323.0       1
336.0       1
Name: count, Length: 285, dtype: int64
cc_card_count
1.0    86363
2.0      538
3.0        3
4.0        1
Name: count, dtype: int64
cc_card_count
1.0    16455
2.0      194
3.0        4
Name: count, dtype: int64
cc_late_payment_count
0.0     69023
1.0      5477
2.0      2627
3.0      1758
4.0      1214
        ...
90.0        1
91.0        1
92.0        2
93.0        1
94.0        3
Name: count, Length: 91, dtype: int64
cc_late_payment_count
0.0     13875
1.0       919
2.0       417
3.0       286
4.0       184
        ...
73.0        2
74.0        1
75.0        1
80.0        1
92.0        1
Name: count, Length: 76, dtype: int64
cc_serious_dpd_count
0.0     72063
1.0      4545
2.0      2369
3.0      1554
4.0      1121
        ...
86.0        1
88.0        1
90.0        1
93.0        1
94.0        1
Name: count, Length: 64, dtype: int64
cc_serious_dpd_count
0.0     14466
1.0       688
2.0       359
3.0       245
4.0       163
5.0       109
6.0       102
7.0        80
8.0        71
9.0        43
10.0       40
11.0       39
12.0       45
13.0       30
14.0       25
15.0       22
16.0       21
17.0       17
18.0       10
19.0        8
20.0        9
21.0        5
22.0        6
23.0        5
24.0        5
25.0        2
26.0        3
27.0        3
28.0        2
29.0        3
30.0        2
31.0        3
32.0        3
33.0        1
34.0        2
35.0        3
36.0        2
38.0        2
39.0        1
41.0        1
42.0        1
47.0        1
49.0        1
72.0        1
74.0        1
75.0        1
92.0        1
Name: count, dtype: int64
pos_loan_count
1.0     89514
2.0     73582
3.0     49753
4.0     31195
5.0     18931
6.0     11252
7.0      6482
8.0      3673
9.0      2158
10.0     1184
11.0      699
12.0      429
13.0      244
14.0      134
15.0       82
16.0       43
17.0       37
18.0       22
19.0       15
20.0        8
21.0        2
22.0        1
23.0        2
24.0        1
26.0        1
Name: count, dtype: int64
pos_loan_count
1.0     14222
2.0     12234
3.0      8085
4.0      5207
5.0      3289
6.0      1881
7.0      1183
8.0       674
9.0       424
10.0      237
11.0      145
12.0       92
13.0       57
14.0       36
15.0       17
16.0       12
17.0        7
18.0        3
19.0        1
21.0        2
Name: count, dtype: int64
pos_late_payment_count
0.0      234761
1.0       23350
2.0        9741
3.0        5536
4.0        3604
          ...
98.0          2
99.0          5
101.0         2
108.0         1
120.0         1
Name: count, Length: 103, dtype: int64
pos_late_payment_count
0.0      39507
1.0       3782
2.0       1488
3.0        842
4.0        546
         ...
95.0         5
96.0        10
97.0         1
146.0        1
169.0        1
Name: count, Length: 88, dtype: int64
pos_serious_dpd_count
0.0      249554
1.0       20538
2.0        7920
3.0        4076
4.0        2373
          ...
94.0          1
95.0          4
96.0          8
108.0         1
120.0         1
Name: count, Length: 62, dtype: int64
pos_serious_dpd_count
0.0      41749
1.0       3271
2.0       1170
3.0        611
4.0        351
5.0        199
6.0        132
7.0         68
8.0         55
9.0         52
10.0        42
11.0        21
12.0        20
13.0        11
14.0        13
15.0         7
16.0        11
17.0         1
18.0         2
19.0         1
20.0         5
21.0         1
22.0         3
23.0         1
24.0         1
73.0         1
86.0         1
88.0         1
93.0         1
95.0         1
96.0         3
145.0        1
169.0        1
Name: count, dtype: int64
pos_active_contracts
0.0       203
1.0       789
2.0       878
3.0      2660
4.0      6221
         ...
222.0       1
226.0       3
228.0       1
231.0       1
271.0       1
Name: count, Length: 212, dtype: int64
pos_active_contracts
0.0        15
1.0       267
2.0       348
3.0       534
4.0      1105
         ...
214.0       1
217.0       1
218.0       1
225.0       1
230.0       1
Name: count, Length: 192, dtype: int64
pos_completed_contracts
0.0      32228
1.0     104597
2.0      67010
3.0      38512
4.0      21321
5.0      11534
6.0       6199
7.0       3323
8.0       1793
9.0        952
10.0       512
11.0       279
12.0       172
13.0        88
14.0        61
15.0        36
16.0        22
17.0        13
18.0        11
19.0         3
20.0         4
21.0         2
24.0         1
42.0         1
45.0         1
46.0         6
47.0         5
48.0        63
49.0        60
50.0        52
51.0       120
52.0       120
53.0        81
54.0        60
55.0        47
56.0        55
57.0        39
58.0        29
59.0         9
60.0         9
61.0         7
62.0         2
65.0         1
77.0         1
78.0         1
81.0         1
85.0         1
Name: count, dtype: int64
pos_completed_contracts
0.0      4784
1.0     17092
2.0     10874
3.0      6410
4.0      3719
5.0      2157
6.0      1150
7.0       616
8.0       401
9.0       212
10.0      120
11.0       59
12.0       43
13.0       31
14.0        9
15.0        3
16.0        3
17.0        5
18.0        2
20.0        1
21.0        2
22.0        1
55.0        1
56.0       13
57.0       14
58.0       19
59.0       21
60.0       15
61.0       18
62.0        7
63.0        3
64.0        1
67.0        1
86.0        1
Name: count, dtype: int64
pos_signed_contracts
0.0     231574
1.0      48234
2.0       7049
3.0       1370
4.0        452
5.0        202
6.0        146
7.0        101
8.0         60
9.0        105
10.0        43
11.0        23
12.0         9
13.0        11
14.0         9
15.0         9
16.0         7
17.0         5
18.0         2
19.0         2
20.0         1
21.0         2
22.0         2
23.0         2
26.0         1
27.0         7
28.0         1
29.0         9
30.0         3
32.0         1
42.0         1
71.0         1
Name: count, dtype: int64
pos_signed_contracts
0.0     37962
1.0      8201
2.0      1210
3.0       241
4.0        85
5.0        32
6.0        14
7.0        14
8.0        14
9.0        15
10.0        4
11.0        2
12.0        1
13.0        2
15.0        2
17.0        2
18.0        1
22.0        1
28.0        1
29.0        2
30.0        1
42.0        1
Name: count, dtype: int64
pos_demand_contracts
0.0      289132
1.0          99
2.0          31
3.0           9
4.0           6
5.0           5
6.0           2
7.0           4
8.0           8
9.0           2
10.0          2
11.0          1
12.0          1
13.0          6
14.0          8
15.0          7
16.0          7
17.0          2
18.0          4
19.0          6
20.0          7
21.0          2
22.0          4
23.0          6
24.0          2
25.0          1
26.0          2
27.0          5
28.0          2
29.0          2
30.0          3
32.0          4
33.0          1
34.0          1
41.0          1
48.0          1
53.0          1
54.0          2
55.0          1
58.0          2
60.0          1
62.0          1
63.0          3
64.0          9
65.0          4
66.0          7
67.0         10
68.0          4
69.0          4
70.0          1
71.0          4
72.0          2
134.0         2
Name: count, dtype: int64
pos_demand_contracts
0.0      47760
1.0         17
2.0          3
3.0          4
4.0          1
5.0          1
7.0          2
8.0          1
13.0         2
14.0         1
18.0         1
19.0         3
22.0         1
27.0         1
32.0         1
36.0         1
39.0         1
44.0         1
71.0         1
74.0         3
137.0        1
144.0        1
Name: count, dtype: int64