In [2]:
import pandas as pd
import numpy as np

In [3]:
train = pd.read_csv(r"Processed Datasets\final_train.csv")

train.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,pos_avg_dpd,pos_max_dpd,pos_avg_dpd_def,pos_max_dpd_def,pos_late_payment_count,pos_serious_dpd_count,pos_active_contracts,pos_completed_contracts,pos_signed_contracts,pos_demand_contracts
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0.0,0.0,0.0,0.0,0.0,0.0,19.0,0.0,0.0,0.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0.0,0.0,0.0,0.0,0.0,0.0,26.0,2.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0.0,0.0,0.0,0.0,0.0,0.0,18.0,2.0,0.0,0.0
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0.0,0.0,0.0,0.0,0.0,0.0,62.0,3.0,1.0,0.0

In [4]:
test = pd.read_csv(r"Processed Datasets\final_test.csv")
test.head()

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,pos_avg_dpd,pos_max_dpd,pos_avg_dpd_def,pos_max_dpd_def,pos_late_payment_count,pos_serious_dpd_count,pos_active_contracts,pos_completed_contracts,pos_signed_contracts,pos_demand_contracts
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,...,0.777778,7.0,0.777778,7.0,1.0,1.0,7.0,2.0,0.0,0.0
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,9.0,1.0,1.0,0.0
2,100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,...,0.944444,18.0,0.000000,0.0,2.0,0.0,32.0,3.0,1.0,0.0
3,100028,Cash loans,F,N,Y,2,315000.0,1575000.0,49018.5,1575000.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,29.0,2.0,0.0,0.0
4,100038,Cash loans,M,Y,N,1,180000.0,625500.0,32067.0,625500.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,12.0,1.0,0.0,0.0

In [8]:
train['SKI_ID_PREV']

KeyError: 'SKI_ID_PREV'

In [7]:
cat_cols = train.drop(columns=['TARGET', 'SK_ID_CURR', 'SK_ID_PREV', 'SK_ID_BUREAU']).select_dtypes(include=['object', 'str'])

KeyError: "['SK_ID_PREV', 'SK_ID_BUREAU'] not found in axis"

In [6]:
for col in train.drop(columns=['SK_ID_CURR', 'TARGET', ]).columns:

_IncompleteInputError: incomplete input (2037545603.py, line 2)